Edited viewDateHistory
Changed it such that viewDateHistory does not have "AttributeError: 'CallbackContext' object has no attribute 'callback_query'"
Also imported another library (From telegram import Bot as bot)